// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ChangeTraining.proto

package ChangeTraining;

public interface MuscleGroupOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ChangeTraining.MuscleGroup)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string muscletype = 1;</code>
   */
  java.lang.String getMuscletype();
  /**
   * <code>string muscletype = 1;</code>
   */
  com.google.protobuf.ByteString
      getMuscletypeBytes();
}
