// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ChangeTraining.proto

package ChangeTraining;

public interface RecordedWorkoutOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ChangeTraining.RecordedWorkout)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string confirmed = 1;</code>
   */
  java.lang.String getConfirmed();
  /**
   * <code>string confirmed = 1;</code>
   */
  com.google.protobuf.ByteString
      getConfirmedBytes();
}
