// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ChangeTraining.proto

package ChangeTraining;

public interface ResponseMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ChangeTraining.ResponseMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string key = 1;</code>
   */
  java.lang.String getKey();
  /**
   * <code>string key = 1;</code>
   */
  com.google.protobuf.ByteString
      getKeyBytes();

  /**
   * <code>string value = 2;</code>
   */
  java.lang.String getValue();
  /**
   * <code>string value = 2;</code>
   */
  com.google.protobuf.ByteString
      getValueBytes();
}
