// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ChangeTraining.proto

package ChangeTraining;

public interface TrainingResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ChangeTraining.TrainingResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string workout = 1;</code>
   */
  java.lang.String getWorkout();
  /**
   * <code>string workout = 1;</code>
   */
  com.google.protobuf.ByteString
      getWorkoutBytes();

  /**
   * <code>int32 reps = 2;</code>
   */
  int getReps();
}
