// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ChangeTraining.proto

package ChangeTraining;

/**
 * Protobuf type {@code ChangeTraining.TrainingResponse}
 */
public  final class TrainingResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ChangeTraining.TrainingResponse)
    TrainingResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TrainingResponse.newBuilder() to construct.
  private TrainingResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TrainingResponse() {
    workout_ = "";
    reps_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private TrainingResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            workout_ = s;
            break;
          }
          case 16: {

            reps_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ChangeTraining.ChangeTrainingImpl.internal_static_ChangeTraining_TrainingResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ChangeTraining.ChangeTrainingImpl.internal_static_ChangeTraining_TrainingResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ChangeTraining.TrainingResponse.class, ChangeTraining.TrainingResponse.Builder.class);
  }

  public static final int WORKOUT_FIELD_NUMBER = 1;
  private volatile java.lang.Object workout_;
  /**
   * <code>string workout = 1;</code>
   */
  public java.lang.String getWorkout() {
    java.lang.Object ref = workout_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      workout_ = s;
      return s;
    }
  }
  /**
   * <code>string workout = 1;</code>
   */
  public com.google.protobuf.ByteString
      getWorkoutBytes() {
    java.lang.Object ref = workout_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      workout_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int REPS_FIELD_NUMBER = 2;
  private int reps_;
  /**
   * <code>int32 reps = 2;</code>
   */
  public int getReps() {
    return reps_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getWorkoutBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, workout_);
    }
    if (reps_ != 0) {
      output.writeInt32(2, reps_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getWorkoutBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, workout_);
    }
    if (reps_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, reps_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ChangeTraining.TrainingResponse)) {
      return super.equals(obj);
    }
    ChangeTraining.TrainingResponse other = (ChangeTraining.TrainingResponse) obj;

    boolean result = true;
    result = result && getWorkout()
        .equals(other.getWorkout());
    result = result && (getReps()
        == other.getReps());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + WORKOUT_FIELD_NUMBER;
    hash = (53 * hash) + getWorkout().hashCode();
    hash = (37 * hash) + REPS_FIELD_NUMBER;
    hash = (53 * hash) + getReps();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ChangeTraining.TrainingResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ChangeTraining.TrainingResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ChangeTraining.TrainingResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ChangeTraining.TrainingResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ChangeTraining.TrainingResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ChangeTraining.TrainingResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ChangeTraining.TrainingResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ChangeTraining.TrainingResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ChangeTraining.TrainingResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ChangeTraining.TrainingResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ChangeTraining.TrainingResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ChangeTraining.TrainingResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ChangeTraining.TrainingResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ChangeTraining.TrainingResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ChangeTraining.TrainingResponse)
      ChangeTraining.TrainingResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ChangeTraining.ChangeTrainingImpl.internal_static_ChangeTraining_TrainingResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ChangeTraining.ChangeTrainingImpl.internal_static_ChangeTraining_TrainingResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ChangeTraining.TrainingResponse.class, ChangeTraining.TrainingResponse.Builder.class);
    }

    // Construct using ChangeTraining.TrainingResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      workout_ = "";

      reps_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ChangeTraining.ChangeTrainingImpl.internal_static_ChangeTraining_TrainingResponse_descriptor;
    }

    @java.lang.Override
    public ChangeTraining.TrainingResponse getDefaultInstanceForType() {
      return ChangeTraining.TrainingResponse.getDefaultInstance();
    }

    @java.lang.Override
    public ChangeTraining.TrainingResponse build() {
      ChangeTraining.TrainingResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ChangeTraining.TrainingResponse buildPartial() {
      ChangeTraining.TrainingResponse result = new ChangeTraining.TrainingResponse(this);
      result.workout_ = workout_;
      result.reps_ = reps_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ChangeTraining.TrainingResponse) {
        return mergeFrom((ChangeTraining.TrainingResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ChangeTraining.TrainingResponse other) {
      if (other == ChangeTraining.TrainingResponse.getDefaultInstance()) return this;
      if (!other.getWorkout().isEmpty()) {
        workout_ = other.workout_;
        onChanged();
      }
      if (other.getReps() != 0) {
        setReps(other.getReps());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ChangeTraining.TrainingResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ChangeTraining.TrainingResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object workout_ = "";
    /**
     * <code>string workout = 1;</code>
     */
    public java.lang.String getWorkout() {
      java.lang.Object ref = workout_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        workout_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string workout = 1;</code>
     */
    public com.google.protobuf.ByteString
        getWorkoutBytes() {
      java.lang.Object ref = workout_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        workout_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string workout = 1;</code>
     */
    public Builder setWorkout(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      workout_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string workout = 1;</code>
     */
    public Builder clearWorkout() {
      
      workout_ = getDefaultInstance().getWorkout();
      onChanged();
      return this;
    }
    /**
     * <code>string workout = 1;</code>
     */
    public Builder setWorkoutBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      workout_ = value;
      onChanged();
      return this;
    }

    private int reps_ ;
    /**
     * <code>int32 reps = 2;</code>
     */
    public int getReps() {
      return reps_;
    }
    /**
     * <code>int32 reps = 2;</code>
     */
    public Builder setReps(int value) {
      
      reps_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 reps = 2;</code>
     */
    public Builder clearReps() {
      
      reps_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ChangeTraining.TrainingResponse)
  }

  // @@protoc_insertion_point(class_scope:ChangeTraining.TrainingResponse)
  private static final ChangeTraining.TrainingResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ChangeTraining.TrainingResponse();
  }

  public static ChangeTraining.TrainingResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TrainingResponse>
      PARSER = new com.google.protobuf.AbstractParser<TrainingResponse>() {
    @java.lang.Override
    public TrainingResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new TrainingResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TrainingResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TrainingResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ChangeTraining.TrainingResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

