// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ChangeTraining.proto

package ChangeTraining;

public interface WorkoutDoneOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ChangeTraining.WorkoutDone)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string done = 1;</code>
   */
  java.lang.String getDone();
  /**
   * <code>string done = 1;</code>
   */
  com.google.protobuf.ByteString
      getDoneBytes();

  /**
   * <code>int32 weight = 2;</code>
   */
  int getWeight();
}
