// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GymClassBooking.proto

package GymClassBooking;

public interface BookingDetailsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GymClassBooking.BookingDetails)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string time = 1;</code>
   */
  java.lang.String getTime();
  /**
   * <code>string time = 1;</code>
   */
  com.google.protobuf.ByteString
      getTimeBytes();

  /**
   * <code>string class = 2;</code>
   */
  java.lang.String getClass_();
  /**
   * <code>string class = 2;</code>
   */
  com.google.protobuf.ByteString
      getClass_Bytes();
}
