// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GymClassBooking.proto

package GymClassBooking;

public interface UserDetailsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GymClassBooking.UserDetails)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string userName = 1;</code>
   */
  java.lang.String getUserName();
  /**
   * <code>string userName = 1;</code>
   */
  com.google.protobuf.ByteString
      getUserNameBytes();

  /**
   * <code>string gym = 2;</code>
   */
  java.lang.String getGym();
  /**
   * <code>string gym = 2;</code>
   */
  com.google.protobuf.ByteString
      getGymBytes();

  /**
   * <code>string password = 3;</code>
   */
  java.lang.String getPassword();
  /**
   * <code>string password = 3;</code>
   */
  com.google.protobuf.ByteString
      getPasswordBytes();
}
