// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProgressAssessment.proto

package ProgressAssessment;

public final class ProgressAssessmentImpl {
  private ProgressAssessmentImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProgressAssessment_AssessmentDetail_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ProgressAssessment_AssessmentDetail_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProgressAssessment_ResponseMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ProgressAssessment_ResponseMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProgressAssessment_BookRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ProgressAssessment_BookRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030ProgressAssessment.proto\022\022ProgressAsse" +
      "ssment\".\n\020AssessmentDetail\022\013\n\003key\030\001 \001(\t\022" +
      "\r\n\005value\030\002 \001(\t\"$\n\017ResponseMessage\022\021\n\tcon" +
      "firmed\030\001 \001(\t\"\037\n\013BookRequest\022\020\n\010username\030" +
      "\001 \001(\t2\322\001\n\022ProgressAssessment\022^\n\raddUserD" +
      "etail\022$.ProgressAssessment.AssessmentDet" +
      "ail\032#.ProgressAssessment.ResponseMessage" +
      "\"\000(\001\022\\\n\022bookNextAssessment\022\037.ProgressAss" +
      "essment.BookRequest\032#.ProgressAssessment" +
      ".ResponseMessage\"\000B.\n\022ProgressAssessment" +
      "B\026ProgressAssessmentImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ProgressAssessment_AssessmentDetail_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ProgressAssessment_AssessmentDetail_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ProgressAssessment_AssessmentDetail_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_ProgressAssessment_ResponseMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ProgressAssessment_ResponseMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ProgressAssessment_ResponseMessage_descriptor,
        new java.lang.String[] { "Confirmed", });
    internal_static_ProgressAssessment_BookRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ProgressAssessment_BookRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ProgressAssessment_BookRequest_descriptor,
        new java.lang.String[] { "Username", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
