// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProgressAssessment.proto

package ProgressAssessment;

public interface ResponseMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ProgressAssessment.ResponseMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string confirmed = 1;</code>
   */
  java.lang.String getConfirmed();
  /**
   * <code>string confirmed = 1;</code>
   */
  com.google.protobuf.ByteString
      getConfirmedBytes();
}
